FROM node:17-alpine as source

RUN apk add --no-cache git g++

WORKDIR /opt/app

COPY package*.json ./
RUN npm ci --ignore-scripts

COPY . .


FROM source as build

WORKDIR /opt/app

RUN npm run build

FROM build as release

ARG NPM_TOKEN
ARG GH_TOKEN

ARG AUTHOR_NAME
ARG AUTHOR_EMAIL
ARG COMMITTER_NAME
ARG COMMITTER_EMAIL

ARG RELEASE_DRY_RUN
ARG RELEASE_DEBUG

ARG NPM_REGISTRY

ENV NPM_TOKEN $NPM_TOKEN
ENV GH_TOKEN $GH_TOKEN

ENV GIT_AUTHOR_NAME $AUTHOR_NAME
ENV GIT_AUTHOR_EMAIL $AUTHOR_EMAIL
ENV GIT_COMMITTER_NAME $COMMITTER_NAME
ENV GIT_COMMITTER_EMAIL $COMMITTER_EMAIL

ENV NPM_CONFIG_REGISTRY $NPM_REGISTRY

WORKDIR /opt/app

RUN npm run release -- ${RELEASE_DRY_RUN:+--dry-run} ${RELEASE_DEBUG:+--debug}
